import "../styles/global.css";
import Navigation from "../components/navigation";

export const metadata = {
  title: {
    template: "%s | Next Movie",
    default: "Next Movie",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
